server:
  port: 8888
spring:
  application:
    name: config-sevice
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/yanghwayeong/Desktop/spring-cloud-config
        git:
          uri: https://github.com/sanchaehwa/spring-cloud-config
#           private Repository ? ???? ?? username, password ??
#          username: [your username]
#          password: [your password]


management:
  endpoint:
    web:
      exposure:
        include: health, busrefresh

