server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/yanghwayeong/Desktop/spring-cloud-config
        git:
          uri: https://github.com/sanchaehwa/spring-cloud-config.git
#           private Repository ? ???? ?? username, password ??
#          username: [your username]
#          password: [your password]


